In [17]:
#import libraries
import pandas as pd
import numpy as np


# Load CSV dataset
df = pd.read_csv("irisdataset.csv")  

#display first 5 rows
df.head()
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [19]:
# Checking missing values

df.isnull().sum()

# there are no missing values

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [20]:
# Fitering the data 
df[df["SepalLengthCm"] > 5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [21]:
df.groupby("SepalWidthCm").mean(numeric_only=True)

                      Id  SepalLengthCm  PetalLengthCm  PetalWidthCm
SepalWidthCm
2.0            61.000000       5.000000       3.500000      1.000000
2.2            84.000000       6.066667       4.500000      1.333333
2.3            69.500000       5.325000       3.250000      0.975000
2.4            73.666667       5.300000       3.600000      1.033333
2.5           101.125000       5.762500       4.512500      1.550000
2.6           103.600000       6.160000       4.880000      1.420000
2.7            96.777778       5.855556       4.622222      1.555556
2.8           103.428571       6.335714       5.042857      1.707143
2.9            75.800000       6.060000       4.350000      1.320000
3.0            88.692308       6.015385       4.234615      1.403846
3.1            73.750000       5.941667       3.600000      1.141667
3.2            73.230769       5.884615       3.753846      1.261538
3.3            83.666667       6.016667       4.200000      1.566667
3.4            47.750000       5.316667       2.466667      0.716667
3.5            28.166667       5.150000       1.416667      0.300000
3.6            46.000000       5.600000       2.833333      0.966667
3.7            27.333333       5.266667       1.500000      0.266667
3.8            63.500000       6.100000       3.300000      0.900000
3.9            11.500000       5.400000       1.500000      0.400000
4.0            15.000000       5.800000       1.200000      0.200000
4.1            33.000000       5.200000       1.500000      0.100000
4.2            34.000000       5.500000       1.400000      0.200000
4.4            16.000000       5.700000       1.500000      0.400000

In [22]:
df.groupby("Species").mean(numeric_only=True)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [23]:
df.groupby("SepalLengthCm").mean(numeric_only=True)

                       Id  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm
4.3             14.000000      3.000000       1.100000      0.100000
4.4             30.333333      3.033333       1.333333      0.200000
4.5             42.000000      2.300000       1.300000      0.300000
4.6             20.500000      3.325000       1.325000      0.225000
4.7             16.500000      3.200000       1.450000      0.200000
4.8             25.400000      3.180000       1.580000      0.200000
4.9             41.666667      2.866667       2.283333      0.533333
5.0             39.200000      3.120000       1.840000      0.430000
5.1             35.111111      3.477778       1.722222      0.400000
5.2             37.500000      3.425000       2.075000      0.475000
5.3             49.000000      3.700000       1.500000      0.200000
5.4             28.666667      3.550000       2.033333      0.516667
5.5             67.000000      2.842857       3.228571      0.900000
5.6             84.666667      2.816667       4.200000      1.416667
5.7             72.250000      3.100000       3.587500      1.100000
5.8             88.428571      2.885714       4.071429      1.400000
5.9             94.333333      3.066667       4.700000      1.700000
6.0             95.166667      2.733333       4.650000      1.500000
6.1             94.166667      2.850000       4.750000      1.416667
6.2            110.750000      2.825000       4.750000      1.725000
6.3            107.222222      2.855556       5.133333      1.811111
6.4            107.857143      2.957143       5.157143      1.871429
6.5            107.200000      3.000000       5.240000      1.900000
6.6             67.500000      2.950000       4.500000      1.350000
6.7            112.125000      3.050000       5.262500      1.962500
6.8            111.333333      3.000000       5.400000      1.933333
6.9            114.000000      3.125000       5.275000      2.050000
7.0             51.000000      3.200000       4.700000      1.400000
7.1            103.000000      3.000000       5.900000      2.100000
7.2            122.000000      3.266667       5.966667      1.966667
7.3            108.000000      2.900000       6.300000      1.800000
7.4            131.000000      2.800000       6.100000      1.900000
7.6            106.000000      3.000000       6.600000      2.100000
7.7            124.000000      3.050000       6.600000      2.200000
7.9            132.000000      3.800000       6.400000      2.000000

In [24]:
df.groupby("PetalLengthCm").mean(numeric_only=True)

                       Id  SepalLengthCm  SepalWidthCm  PetalWidthCm
PetalLengthCm
1.0             23.000000       4.600000      3.600000      0.200000
1.1             14.000000       4.300000      3.000000      0.100000
1.2             25.500000       5.400000      3.600000      0.200000
1.3             31.714286       4.842857      3.228571      0.257143
1.4             21.833333       4.916667      3.333333      0.216667
1.5             24.714286       5.128571      3.535714      0.221429
1.6             31.000000       4.914286      3.342857      0.285714
1.7             17.500000       5.400000      3.600000      0.350000
1.9             35.000000       4.950000      3.600000      0.300000
3.0             99.000000       5.100000      2.500000      1.100000
3.3             76.000000       4.950000      2.350000      1.000000
3.5             70.500000       5.350000      2.300000      1.000000
3.6             65.000000       5.600000      2.900000      1.300000
3.7             82.000000       5.500000      2.400000      1.000000
3.8             81.000000       5.500000      2.400000      1.100000
3.9             71.000000       5.533333      2.633333      1.233333
4.0             74.400000       5.780000      2.480000      1.220000
4.1             85.666667       5.700000      2.833333      1.200000
4.2             87.500000       5.725000      2.900000      1.325000
4.3             86.500000       6.300000      2.900000      1.300000
4.4             80.250000       6.275000      2.750000      1.325000
4.5             75.125000       5.775000      2.875000      1.512500
4.6             68.666667       6.400000      2.900000      1.400000
4.7             66.600000       6.440000      3.060000      1.420000
4.8            103.500000       6.225000      2.950000      1.700000
4.9            100.000000       6.240000      2.820000      1.720000
5.0            114.750000       6.175000      2.550000      1.775000
5.1            122.625000       6.125000      2.875000      1.925000
5.2            147.000000       6.600000      3.000000      2.150000
5.3            114.000000       6.400000      2.950000      2.100000
5.4            144.500000       6.550000      3.250000      2.200000
5.5            122.666667       6.566667      3.033333      1.900000
5.6            129.833333       6.366667      2.933333      2.050000
5.7            130.333333       6.766667      3.266667      2.300000
5.8            114.666667       6.800000      2.833333      1.866667
5.9            123.500000       6.950000      3.100000      2.200000
6.0            113.500000       6.750000      3.250000      2.150000
6.1            125.666667       7.433333      3.133333      2.233333
6.3            108.000000       7.300000      2.900000      1.800000
6.4            132.000000       7.900000      3.800000      2.000000
6.6            106.000000       7.600000      3.000000      2.100000
6.7            120.500000       7.700000      3.300000      2.100000
6.9            119.000000       7.700000      2.600000      2.300000